name: Keep Streamlit Awake

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone Repository
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@://github.com{{ github.repository }}.git .

      - name: Create Empty Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Keepalive ping from GitHub Actions"
          git push origin HEAD:${{ github.ref_name }}
