[client]
showSidebarNavigation = true

[theme]
font = "'Inter':https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
baseRadius = "12px"
primaryColor = "#5A94E8"
textColor = "#49618D"
base = "light"

backgroundColor = "white"
secondaryBackgroundColor = "#ddefff"


[theme.sidebar]
font = "'Inter':https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
backgroundColor = "#1e293b"
textColor = "#f1f5f9"
secondaryBackgroundColor = "#334155"

[server]
runOnSave = false

# (Watchdog dễ bị nháy kép) -> quét định kỳ (Poll)
fileWatcherType = "poll"

[browser]
gatherUsageStats = false